"""AI Compliance Assistant Module for Legal Metrology Verification.

Provides natural language explanations, violation summaries, and actionable remediation
guidance grounded strictly in the generated compliance verification report.
"""
from __future__ import annotations

from dataclasses import dataclass, field
import logging
import re
from typing import Any, Dict, List, Optional, Set

logger = logging.getLogger(__name__)


@dataclass
class AssistantResponse:
    """Structured response from the AI Compliance Assistant."""

    question: str
    intent: str
    answer: str
    key_findings: List[str] = field(default_factory=list)
    action_items: List[Dict[str, str]] = field(default_factory=list)
    relevant_rules: List[str] = field(default_factory=list)
    overall_status: str = "UNKNOWN"
    compliance_score: float = 0.0
    risk_level: str = "UNKNOWN"

    def to_dict(self) -> Dict[str, Any]:
        return {
            "question": self.question,
            "intent": self.intent,
            "answer": self.answer,
            "key_findings": self.key_findings,
            "action_items": self.action_items,
            "relevant_rules": self.relevant_rules,
            "overall_status": self.overall_status,
            "compliance_score": self.compliance_score,
            "risk_level": self.risk_level,
        }


class AIComplianceAssistant:
    """Explainable and advisory natural language compliance assistant.

    Answers compliance questions strictly using the data in the validation report
    without altering any verification outcomes.
    """

    def __init__(self, report: Dict[str, Any]) -> None:
        """Initialize the assistant with a generated compliance verification report.

        Args:
            report: Compliance verification report generated by ComplianceEngine or SmartRuleEngine.
        """
        self.report = report or {}
        self.overall_status = str(self.report.get("overall_status", "UNKNOWN")).upper()
        self.score = float(self.report.get("compliance_score", 0.0))
        self.risk_level = str(self.report.get("risk_level", "UNKNOWN")).upper()
        self.results = self.report.get("results", [])
        self.explanations = self.report.get("explanations", [])
        self.recommendations = self.report.get("recommendations", [])

        # Categorize results by status
        self.failed_rules = [r for r in self.results if r.get("status") == "FAIL"]
        self.warning_rules = [r for r in self.results if r.get("status") == "WARNING"]
        self.passed_rules = [r for r in self.results if r.get("status") == "PASS"]
        self.not_applicable_rules = [r for r in self.results if r.get("status") == "NOT_APPLICABLE"]

    def _format_rule_ref(self, rule: Dict[str, Any]) -> str:
        rule_id = rule.get("rule_id", "Rule")
        rule_name = rule.get("rule_name", "")
        return f"{rule_name} ({rule_id})" if rule_name else rule_id

    def explain_failure(self, question: str = "Why did this product fail?") -> AssistantResponse:
        """Explain why the product failed compliance or received warnings."""
        if self.overall_status == "COMPLIANT":
            return AssistantResponse(
                question=question,
                intent="why_failed",
                answer=f"This product did not fail. It is fully COMPLIANT with a score of {self.score:.1f}% (Risk Level: {self.risk_level}). All applicable Legal Metrology declarations were verified successfully.",
                key_findings=["All mandatory declarations are present and validly formatted."],
                overall_status=self.overall_status,
                compliance_score=self.score,
                risk_level=self.risk_level,
            )

        findings = []
        action_items = []
        relevant_rules = []

        for fail in self.failed_rules:
            ref = self._format_rule_ref(fail)
            msg = fail.get("message", "Mandatory declaration missing or invalid.")
            findings.append(f"[FAIL] {ref}: {msg}")
            relevant_rules.append(fail.get("rule_id", ""))
            if fail.get("recommendation"):
                action_items.append({
                    "rule_id": fail.get("rule_id", ""),
                    "priority": "Immediate",
                    "action": fail.get("recommendation", ""),
                })

        for warn in self.warning_rules:
            ref = self._format_rule_ref(warn)
            msg = warn.get("message", "Requires verification.")
            findings.append(f"[WARNING] {ref}: {msg}")
            relevant_rules.append(warn.get("rule_id", ""))
            if warn.get("recommendation"):
                action_items.append({
                    "rule_id": warn.get("rule_id", ""),
                    "priority": "Recommended",
                    "action": warn.get("recommendation", ""),
                })

        if self.failed_rules:
            answer = (
                f"The product received a NON_COMPLIANT status (Score: {self.score:.1f}%, Risk: {self.risk_level}) "
                f"due to {len(self.failed_rules)} mandatory violation(s)"
                + (f" and {len(self.warning_rules)} warning(s)." if self.warning_rules else ".")
            )
        else:
            answer = (
                f"The product is PARTIALLY_COMPLIANT (Score: {self.score:.1f}%, Risk: {self.risk_level}) "
                f"with {len(self.warning_rules)} warning(s) requiring verification."
            )

        return AssistantResponse(
            question=question,
            intent="why_failed",
            answer=answer,
            key_findings=findings,
            action_items=action_items,
            relevant_rules=relevant_rules,
            overall_status=self.overall_status,
            compliance_score=self.score,
            risk_level=self.risk_level,
        )

    def list_violations(self, question: str = "Which rules were violated?") -> AssistantResponse:
        """List all violated and warning rules."""
        if not self.failed_rules and not self.warning_rules:
            return AssistantResponse(
                question=question,
                intent="violated_rules",
                answer="No compliance rules were violated. All evaluated declarations passed Legal Metrology requirements.",
                key_findings=["Zero violations detected."],
                overall_status=self.overall_status,
                compliance_score=self.score,
                risk_level=self.risk_level,
            )

        findings = []
        relevant_rules = []
        for r in self.failed_rules:
            findings.append(f"Violation: {self._format_rule_ref(r)} — {r.get('message', 'Declaration missing or invalid')}")
            relevant_rules.append(r.get("rule_id", ""))

        for r in self.warning_rules:
            findings.append(f"Warning: {self._format_rule_ref(r)} — {r.get('message', 'Unconfirmed declaration')}")
            relevant_rules.append(r.get("rule_id", ""))

        answer = f"A total of {len(self.failed_rules)} violation(s) and {len(self.warning_rules)} warning(s) were identified."

        return AssistantResponse(
            question=question,
            intent="violated_rules",
            answer=answer,
            key_findings=findings,
            relevant_rules=relevant_rules,
            overall_status=self.overall_status,
            compliance_score=self.score,
            risk_level=self.risk_level,
        )

    def get_remediation_guide(self, question: str = "How can I fix the violations?") -> AssistantResponse:
        """Provide step-by-step corrective actions to fix all issues."""
        if not self.recommendations:
            return AssistantResponse(
                question=question,
                intent="how_to_fix",
                answer="No corrective actions are needed. The packaging declarations satisfy all Legal Metrology standards.",
                key_findings=["No remediation required."],
                overall_status=self.overall_status,
                compliance_score=self.score,
                risk_level=self.risk_level,
            )

        action_items = []
        findings = []
        relevant_rules = []

        for rec in self.recommendations:
            r_id = rec.get("rule_id", "")
            pri = rec.get("priority", "Recommended")
            action = rec.get("recommendation", "")
            r_name = rec.get("rule_name", r_id)

            action_items.append({
                "rule_id": r_id,
                "rule_name": r_name,
                "priority": pri,
                "action": action,
            })
            findings.append(f"[{pri.upper()}] {r_name} ({r_id}): {action}")
            relevant_rules.append(r_id)

        answer = f"To achieve full compliance, perform the following {len(action_items)} corrective action(s) in order of priority:"

        return AssistantResponse(
            question=question,
            intent="how_to_fix",
            answer=answer,
            key_findings=findings,
            action_items=action_items,
            relevant_rules=relevant_rules,
            overall_status=self.overall_status,
            compliance_score=self.score,
            risk_level=self.risk_level,
        )

    def get_missing_declarations(self, question: str = "Which declaration is missing?") -> AssistantResponse:
        """Identify missing mandatory packaging declarations."""
        missing = []
        relevant_rules = []

        for r in self.failed_rules:
            msg = str(r.get("message", "")).lower()
            val = r.get("actual_value")
            if "missing" in msg or "absent" in msg or val is None or str(val).strip() in {"", "none", "null"}:
                missing.append(f"{self._format_rule_ref(r)} is not declared on the package label.")
                relevant_rules.append(r.get("rule_id", ""))

        if not missing:
            answer = "No mandatory declarations are missing from the package label."
        else:
            answer = f"{len(missing)} mandatory declaration(s) are missing from the packaging label."

        return AssistantResponse(
            question=question,
            intent="missing_declarations",
            answer=answer,
            key_findings=missing if missing else ["All mandatory declarations are present."],
            relevant_rules=relevant_rules,
            overall_status=self.overall_status,
            compliance_score=self.score,
            risk_level=self.risk_level,
        )

    def get_highest_priority_issue(self, question: str = "What is the highest priority issue?") -> AssistantResponse:
        """Determine and explain the most urgent regulatory issue requiring attention."""
        if not self.failed_rules and not self.warning_rules:
            return AssistantResponse(
                question=question,
                intent="highest_priority_issue",
                answer="There are no compliance issues. The product meets all Legal Metrology requirements.",
                key_findings=["No critical issues detected."],
                overall_status=self.overall_status,
                compliance_score=self.score,
                risk_level=self.risk_level,
            )

        # High priority failure takes top precedence
        top_issue = self.failed_rules[0] if self.failed_rules else self.warning_rules[0]
        rule_id = top_issue.get("rule_id", "")
        rule_name = top_issue.get("rule_name", "Declaration")
        status = top_issue.get("status", "FAIL")
        msg = top_issue.get("message", "Regulatory issue detected.")
        rec = top_issue.get("recommendation", "Review packaging declaration.")

        priority = "Immediate" if status == "FAIL" else "Recommended"
        answer = f"The highest priority issue is {rule_name} ({rule_id}) which resulted in {status} [{priority} Action Required]."

        action_item = {
            "rule_id": rule_id,
            "rule_name": rule_name,
            "priority": priority,
            "action": rec,
        }

        return AssistantResponse(
            question=question,
            intent="highest_priority_issue",
            answer=answer,
            key_findings=[f"{rule_name} ({rule_id}): {msg}"],
            action_items=[action_item],
            relevant_rules=[rule_id],
            overall_status=self.overall_status,
            compliance_score=self.score,
            risk_level=self.risk_level,
        )

    def ask(self, question: str) -> Dict[str, Any]:
        """Process a natural language question regarding the compliance report.

        Args:
            question: Free-form text query from user.

        Returns:
            Structured dictionary with answer, key findings, and action items.
        """
        q_lower = question.lower().strip()

        # Specific actionable intents take precedence
        if any(k in q_lower for k in ["fix", "correct", "recommend", "how to", "remediate", "action"]):
            res = self.get_remediation_guide(question)
        elif any(k in q_lower for k in ["missing", "absent", "not found", "omitted", "lacking"]):
            res = self.get_missing_declarations(question)
        elif any(k in q_lower for k in ["highest", "priority", "most critical", "urgent", "top issue", "main issue"]):
            res = self.get_highest_priority_issue(question)
        elif any(k in q_lower for k in ["why", "fail", "reason", "cause", "rejected"]):
            res = self.explain_failure(question)
        elif any(k in q_lower for k in ["violation", "violated", "rule", "which rules", "broken"]):
            res = self.list_violations(question)
        elif any(k in q_lower for k in ["summary", "overview", "status", "score", "how is"]):
            res = self.explain_failure(question)
        else:
            res = self.explain_failure(question)

        return res.to_dict()


# ---------------------------------------------------------------------------
# Convenience functions
# ---------------------------------------------------------------------------

def ask_compliance_assistant(report: Dict[str, Any], question: str) -> Dict[str, Any]:
    """Ask a question to the AI Compliance Assistant regarding a report."""
    assistant = AIComplianceAssistant(report)
    return assistant.ask(question)


def generate_compliance_summary(report: Dict[str, Any]) -> Dict[str, Any]:
    """Generate an executive natural language compliance summary."""
    assistant = AIComplianceAssistant(report)
    return assistant.explain_failure("What is the compliance status and summary of this product?").to_dict()
