"""Field label definitions used by the product field extractor."""

FIELD_LABELS = {
    "mrp": (
        "mrp",
        "m.r.p",
        "maximum retail price",
        "max retail price",
    ),
    "net_quantity": (
        "net qty",
        "net quantity",
        "net wt",
        "net weight",
        "net contents",
        "net volume",
    ),
    "batch_number": (
        "batch",
        "batch no",
        "batch number",
        "lot",
        "lot no",
        "lot number",
    ),
    "manufacturing_date": (
        "mfg",
        "mfg date",
        "mfg dt",
        "mfd",
        "mfd date",
        "manufactured on",
        "manufactured date",
        "pkd",
        "pkd date",
        "packed on",
        "packed date",
    ),
    "import_date": (
        "import date",
        "import dt",
        "imported on",
        "imported date",
    ),
    "country_of_origin": (
        "country of origin",
        "made in",
        "product of",
        "origin",
    ),
    "manufacturer": (
        "mfd by",
        "manufactured by",
        "manufactured and packed by",
        "produced by",
    ),
    "importer": (
        "importer",
        "imported by",
        "imported and packed by",
        "imp. by",
    ),
    "customer_care_details": (
        "customer care",
        "consumer care",
        "helpline",
        "feedback",
        "contact us",
        "toll free",
        "care line",
    ),
    "product_name": (
        "product",
        "product name",
        "item name",
        "commodity",
    ),
    "brand_name": (
        "brand",
        "brand name",
        "trademark",
        "tm",
    ),
}